project:
  type: website

website:
  title: "Cell Composition Dashboard"
  navbar:
    left:
      - text: "Home"
        href: composition-dashboard.html

format:
  html:
    theme: cosmo    # <- these must be indented under html
    toc: true
